---
- name: Install by APT | Apt-key add repo key
  apt_key:
    keyserver: "{{ clickhouse_repo_keyserver }}"
    id: "{{ clickhouse_repo_key }}"
  become: true

- name: Install by APT | Repo installation
  apt_repository:
    repo: "{{ clickhouse_repo }}"
    state: present
  become: true

- name: Install by APT | Package installation
  apt:
    name: "{{ 'clickhouse-common-static=' + clickhouse_version }}"
    state: present
    update_cache: true
  become: true

- name: Install by APT | Package installation
  apt:
    name: "{{ 'clickhouse-server=' + clickhouse_version }}"
    state: present
    update_cache: true
  become: true

- name: Install by APT | Package installation
  apt:
    name: "{{ 'clickhouse-client=' + clickhouse_version }}"
    state: present
    update_cache: true
  become: true
