---
# tasks file for clickhouse
- include_tasks: precheck.yml

- include_tasks: params.yml

- include_tasks: install/apt.yml

- include_tasks: configure/sys.yml

- name: "Notify Handlers Now"
  meta: flush_handlers

- include_tasks: service.yml

- name: "Wait for Clickhouse Server to Become Ready"
  wait_for:
    port: "{{ clickhouse_tcp_port }}"
    delay: "{{ clickhouse_ready_delay }}"
