---
ansible_user: ansible
clickhouse_supported: true

clickhouse_repo: "deb https://repo.clickhouse.tech/deb/stable/ main/"
clickhouse_repo_keyserver: keyserver.ubuntu.com
clickhouse_repo_key: E0C56BD4

clickhouse_version: "20.12.5.14"

clickhouse_path_configdir: "/etc/clickhouse-server"
clickhouse_path_logdir: "/var/log/clickhouse-server"
clickhouse_service: "clickhouse-server.service"

max_memory_usage: 10000000000
max_memory_usage_for_user: 10000000000

clickhouse_tcp_port: 9000
clickhouse_ready_delay: 5

clickhouse_logger:
  level: trace
  log: "{{ clickhouse_path_logdir }}/clickhouse-server.log"
  errorlog: "{{ clickhouse_path_logdir }}/clickhouse-server.err.log"
  size: 1000M
  count: 10

clickhouse_defuser_password_sha256_hex: "ae5deb822e0d71992900471a7199d0d95b8e7c9d05c40a8245a281fd2c1d6684"
